[bans]
multiple-versions = "warn"
wildcards = "warn"
allow-wildcard-paths = true

deny = [
    { name = "openssl", version = "<0.10.60" },
]

skip = []
skip-tree = []

[advisories]
yanked       = "deny"
unmaintained = "all"
unsound      = "all"
ignore       = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]
private = { ignore = true }

[sources]
unknown-git       = "deny"
unknown-registry  = "deny"
required-git-spec = "rev"

allow-git = []

[sources.allow-org]
github = []
