blank_issues_enabled: false
contact_links:
  - name: Gorka Community Pachca
    url: https://app.pachca.com/join?invite_token=EakW3nIgma_ezqFc&company_name=Gorka+Community&company_id=416542
    about: Get free help from the Gorka community
  - name: Gorka Community Discussion
    url: https://github.com/MiCkEyZzZ/gorka/discussions
    about: Get free help from the Gorka community
